pub fn find_by_id(play_region: u32) -> Option<&'static PlayRegion> {
    PLAY_REGIONS.iter().find(|r| r.id == play_region)
}

pub struct PlayRegion {
    pub map: &'static str,
    pub name: &'static str,
    pub id: u32,
}

// This is a list I got from Dasaav. Not my own work.
// TODO: make this configurable so people can add custom areas
const PLAY_REGIONS: [PlayRegion; 210] = [
    PlayRegion { id: 6100090, map: "Limgrave", name: "Church of Dragon Communion"},
    PlayRegion { id: 6100000, map: "Limgrave", name: "The First Step, Church of Elleh"},
    PlayRegion { id: 6100001, map: "Limgrave", name: "Seaside Ruins"},
    PlayRegion { id: 6100004, map: "Limgrave", name: "Mistwood Outskirts, Fort Haight West"},
    PlayRegion { id: 6100002, map: "Limgrave", name: "Agheel Lake North, Murkwater Coast, Gatefront Ruins"},
    PlayRegion { id: 6100003, map: "Limgrave", name: "Summonwater Village Outskirts"},
    PlayRegion { id: 6100010, map: "Limgrave", name: "Waypoint Ruins Cellar"},
    PlayRegion { id: 3002001, map: "Limgrave", name: "Stormfoot Catacombs"},
    PlayRegion { id: 3004001, map: "Limgrave", name: "Murkwater Catacombs"},
    PlayRegion { id: 3103001, map: "Limgrave", name: "Groveside Cave"},
    PlayRegion { id: 3115001, map: "Limgrave", name: "Coastal Cave"},
    PlayRegion { id: 3100001, map: "Limgrave", name: "Murkwater Cave"},
    PlayRegion { id: 3117001, map: "Limgrave", name: "Highroad Cave"},
    PlayRegion { id: 3201001, map: "Limgrave", name: "Limgrave Tunnels"},
    PlayRegion { id: 1800090, map: "Stranded Graveyard", name: "Cave of Knowledge"},
    PlayRegion { id: 1800001, map: "Stranded Graveyard", name: "Stranded Graveyard"},
    PlayRegion { id: 6101000, map: "Stormhill", name: "Stormhill"},
    PlayRegion { id: 6101010, map: "Stormhill", name: "Margit, the Fell Omen"},
    PlayRegion { id: 3011001, map: "Stormhill", name: "Deathtouched Catacombs"},
    PlayRegion { id: 3410090, map: "Stormhill", name: "Divine Tower of Limgrave"},
    PlayRegion { id: 6102001, map: "Weeping Peninsula", name: "Castle Morne"},
    PlayRegion { id: 6102020, map: "Weeping Peninsula", name: "Morne Moangrave"},
    PlayRegion { id: 6102000, map: "Weeping Peninsula", name: "Weeping Peninsula East"},
    PlayRegion { id: 6102002, map: "Weeping Peninsula", name: "Weeping Peninsula West"},
    PlayRegion { id: 3001001, map: "Weeping Peninsula", name: "Impaler's Catacombs"},
    PlayRegion { id: 3000001, map: "Weeping Peninsula", name: "Tombsward Catacombs"},
    PlayRegion { id: 3101001, map: "Weeping Peninsula", name: "Earthbore Cave"},
    PlayRegion { id: 3102001, map: "Weeping Peninsula", name: "Tombsward Cave"},
    PlayRegion { id: 3200001, map: "Weeping Peninsula", name: "Morne Tunnel"},
    PlayRegion { id: 1000001, map: "Stormveil Castle", name: "Stormveil Main Gate, Stormveil Cliffside"},
    PlayRegion { id: 1000006, map: "Stormveil Castle", name: "Gateside Chamber"},
    PlayRegion { id: 1000003, map: "Stormveil Castle", name: "Rampart Tower"},
    PlayRegion { id: 1000005, map: "Stormveil Castle", name: "Liftside Chamber, Secluded Cell"},
    PlayRegion { id: 1000000, map: "Stormveil Castle", name: "Godrick the Grafted"},
    PlayRegion { id: 6200001, map: "Liurnia of the Lakes", name: "Liurnia South-East"},
    PlayRegion { id: 6200004, map: "Liurnia of the Lakes", name: "Liurnia East"},
    PlayRegion { id: 6200008, map: "Liurnia of the Lakes", name: "Behind Caria Manor"},
    PlayRegion { id: 3105090, map: "Liurnia of the Lakes", name: "Slumbering Wolf's Shack"},
    PlayRegion { id: 6200000, map: "Liurnia of the Lakes", name: "Liurnia South"},
    PlayRegion { id: 6200002, map: "Liurnia of the Lakes", name: "Liurnia South-West"},
    PlayRegion { id: 6200005, map: "Liurnia of the Lakes", name: "Liurnia West"},
    PlayRegion { id: 6200003, map: "Liurnia of the Lakes", name: "Kingsrealm Ruins"},
    PlayRegion { id: 6200007, map: "Liurnia of the Lakes", name: "Main Caria Manor Gate"},
    PlayRegion { id: 6200007, map: "Liurnia of the Lakes", name: "Caria Manor"},
    PlayRegion { id: 6200007, map: "Liurnia of the Lakes", name: "Manor Lower Level"},
    PlayRegion { id: 6200010, map: "Liurnia of the Lakes", name: "Royal Moongazing Grounds"},
    PlayRegion { id: 6200006, map: "Liurnia of the Lakes", name: "The Ravine"},
    PlayRegion { id: 3006001, map: "Liurnia of the Lakes", name: "Cliffbottom Catacombs"},
    PlayRegion { id: 3003001, map: "Liurnia of the Lakes", name: "Road's End Catacombs"},
    PlayRegion { id: 3005001, map: "Liurnia of the Lakes", name: "Black Knife Catacombs"},
    PlayRegion { id: 3104001, map: "Liurnia of the Lakes", name: "Stillwater Cave"},
    PlayRegion { id: 3105001, map: "Liurnia of the Lakes", name: "Lakeside Crystal Cave"},
    PlayRegion { id: 3106001, map: "Liurnia of the Lakes", name: "Academy Crystal Cave"},
    PlayRegion { id: 1400011, map: "Liurnia of the Lakes", name: "Main Academy Gate"},
    PlayRegion { id: 3202001, map: "Liurnia of the Lakes", name: "Raya Lucaria Crystal Tunnel"},
    PlayRegion { id: 3411090, map: "Liurnia of the Lakes", name: "Divine Tower of Liurnia"},
    PlayRegion { id: 6201000, map: "Bellum Highway", name: "Bellum Highway"},
    PlayRegion { id: 6200090, map: "Bellum Highway", name: "Grand Lift of Dectus, Jarburg"},
    PlayRegion { id: 3920002, map: "Ruin-Strewn Precipice", name: "Ruin-Strewn Precipice"},
    PlayRegion { id: 3920003, map: "Ruin-Strewn Precipice", name: "Ruin-Strewn Precipice Overlook"},
    PlayRegion { id: 3920000, map: "Ruin-Strewn Precipice", name: "Magma Wyrm Makar"},
    PlayRegion { id: 6202000, map: "Moonlight Altar", name: "Moonlight Altar"},
    PlayRegion { id: 1400013, map: "Academy of Raya Lucaria", name: "Church of the Cuckoo"},
    PlayRegion { id: 1400015, map: "Academy of Raya Lucaria", name: "Schoolhouse Classroom"},
    PlayRegion { id: 1400010, map: "Academy of Raya Lucaria", name: "Debate Parlor"},
    PlayRegion { id: 1400000, map: "Academy of Raya Lucaria", name: "Raya Lucaria Grand Library"},
    PlayRegion { id: 6300005, map: "Altus Plateau", name: "Rampartside Path"},
    PlayRegion { id: 6300000, map: "Altus Plateau", name: "Stormcaller Church, Lux Ruins"},
    PlayRegion { id: 6300001, map: "Altus Plateau", name: "The Shaded Castle"},
    PlayRegion { id: 6300002, map: "Altus Plateau", name: "Altus Highway Junction"},
    PlayRegion { id: 6300030, map: "Altus Plateau", name: "Castellan's Hall"},
    PlayRegion { id: 6300003, map: "Altus Plateau", name: "Forest-Spanning Greatbridge"},
    PlayRegion { id: 3012001, map: "Altus Plateau", name: "Unsightly Catacombs"},
    PlayRegion { id: 3008001, map: "Altus Plateau", name: "Sainted Hero's Grave"},
    PlayRegion { id: 3119001, map: "Altus Plateau", name: "Sage's Cave"},
    PlayRegion { id: 3118001, map: "Altus Plateau", name: "Perfumer's Grotto"},
    PlayRegion { id: 6300004, map: "Altus Plateau", name: "Dominula, Windmill Village, Road of Iniquity Side Path"},
    PlayRegion { id: 3204001, map: "Altus Plateau", name: "Old Altus Tunnel"},
    PlayRegion { id: 3205001, map: "Altus Plateau", name: "Altus Tunnel"},
    PlayRegion { id: 6302000, map: "Mt. Gelmir", name: "Ninth Mt. Gelmir Campsite"},
    PlayRegion { id: 6302001, map: "Mt. Gelmir", name: "Road of Iniquity"},
    PlayRegion { id: 6302002, map: "Mt. Gelmir", name: "Seethewater Terminus, Primeval Sorcerer Azur"},
    PlayRegion { id: 3007001, map: "Mt. Gelmir", name: "Wyndham Catacombs"},
    PlayRegion { id: 3009001, map: "Mt. Gelmir", name: "Gelmir Hero's Grave"},
    PlayRegion { id: 3107001, map: "Mt. Gelmir", name: "Seethewater Cave"},
    PlayRegion { id: 3109001, map: "Mt. Gelmir", name: "Volcano Cave"},
    PlayRegion { id: 6301000, map: "Capital Outskirts", name: "Capital Outskirts"},
    PlayRegion { id: 6301090, map: "Capital Outskirts", name: "Capital Rampart"},
    PlayRegion { id: 3013091, map: "Capital Outskirts", name: "Auriza Side Tomb"},
    PlayRegion { id: 3010001, map: "Capital Outskirts", name: "Auriza Hero's Grave"},
    PlayRegion { id: 3412011, map: "Capital Outskirts", name: "Sealed Tunnel"},
    PlayRegion { id: 3412090, map: "Capital Outskirts", name: "Divine Tower of West Altus"},
    PlayRegion { id: 1600012, map: "Volcano Manor", name: "Volcano Manor"},
    PlayRegion { id: 1600014, map: "Volcano Manor", name: "Prison Town Church"},
    PlayRegion { id: 1600010, map: "Volcano Manor", name: "Temple of Eiglay"},
    PlayRegion { id: 1600016, map: "Volcano Manor", name: "Guest Hall"},
    PlayRegion { id: 1600006, map: "Volcano Manor", name: "Audience Pathway"},
    PlayRegion { id: 1600020, map: "Volcano Manor", name: "Abductor Virgin"},
    PlayRegion { id: 1600022, map: "Volcano Manor", name: "Subterranean Inquisition Chamber"},
    PlayRegion { id: 1600000, map: "Volcano Manor", name: "Rykard, Lord of Blasphemy"},
    PlayRegion { id: 1100010, map: "Leyndell, Royal Capital", name: "Erdtree Sanctuary"},
    PlayRegion { id: 1100012, map: "Leyndell, Royal Capital", name: "East Capital Rampart"},
    PlayRegion { id: 1100015, map: "Leyndell, Royal Capital", name: "Lower Capital Church"},
    PlayRegion { id: 1100013, map: "Leyndell, Royal Capital", name: "Avenue Balcony"},
    PlayRegion { id: 1100001, map: "Leyndell, Royal Capital", name: "Queen's Bedchamber"},
    PlayRegion { id: 1100016, map: "Leyndell, Royal Capital", name: "West Capital Rampart, Fortified Manor, First Floor"},
    PlayRegion { id: 1100017, map: "Leyndell, Royal Capital", name: "Divine Bridge"},
    PlayRegion { id: 1100000, map: "Leyndell, Royal Capital", name: "Elden Throne"},
    PlayRegion { id: 3500002, map: "Subterranean Shunning-Grounds", name: "Underground Roadside"},
    PlayRegion { id: 3500008, map: "Subterranean Shunning-Grounds", name: "Forsaken Depths"},
    PlayRegion { id: 3500010, map: "Subterranean Shunning-Grounds", name: "Leyndell Catacombs"},
    PlayRegion { id: 3500011, map: "Subterranean Shunning-Grounds", name: "Leyndell Catacombs Part II"},
    PlayRegion { id: 3500092, map: "Subterranean Shunning-Grounds", name: "Frenzied Flame Proscription"},
    PlayRegion { id: 3500000, map: "Subterranean Shunning-Grounds", name: "Cathedral of the Forsaken"},
    PlayRegion { id: 1105011, map: "Leyndell, Ashen Capital", name: "Leyndell, Capital of Ash"},
    PlayRegion { id: 1105001, map: "Leyndell, Ashen Capital", name: "Queen's Bedchamber "},
    PlayRegion { id: 1105092, map: "Leyndell, Ashen Capital", name: "Divine Bridge "},
    PlayRegion { id: 1105000, map: "Leyndell, Ashen Capital", name: "Elden Throne "},
    PlayRegion { id: 1900000, map: "Stone Platform", name: "Fractured Marika"},
    PlayRegion { id: 1900001, map: "Stone Platform", name: "Elden Beast"},
    PlayRegion { id: 6400001, map: "Caelid", name: "Central Caelid"},
    PlayRegion { id: 6400000, map: "Caelid", name: "Caelid North"},
    PlayRegion { id: 6400002, map: "Caelid", name: "Chamber Outside the Plaza"},
    PlayRegion { id: 6400010, map: "Caelid", name: "Redmane Castle Plaza"},
    PlayRegion { id: 6400040, map: "Caelid", name: "Starscourge Radahn"},
    PlayRegion { id: 3014001, map: "Caelid", name: "Minor Erdtree Catacombs"},
    PlayRegion { id: 3015001, map: "Caelid", name: "Caelid Catacombs"},
    PlayRegion { id: 3016001, map: "Caelid", name: "War-Dead Catacombs"},
    PlayRegion { id: 3120001, map: "Caelid", name: "Abandoned Cave"},
    PlayRegion { id: 3121001, map: "Caelid", name: "Gaol Cave"},
    PlayRegion { id: 3207001, map: "Caelid", name: "Gael Tunnel"},
    PlayRegion { id: 3207002, map: "Caelid", name: "Gael Tunnel Part II"},
    PlayRegion { id: 3207090, map: "Caelid", name: "Rear Gael Tunnel Entrance"},
    PlayRegion { id: 3208001, map: "Caelid", name: "Sellia Crystal Tunnel"},
    PlayRegion { id: 6400020, map: "Caelid", name: "Chair-Crypt of Sellia"},
    PlayRegion { id: 6401000, map: "Swamp of Aeonia", name: "Swamp of Aeonia"},
    PlayRegion { id: 6402000, map: "Greyoll's Dragonbarrow", name: "Dragonbarrow"},
    PlayRegion { id: 3111001, map: "Greyoll's Dragonbarrow", name: "Sellia Hideaway"},
    PlayRegion { id: 3110001, map: "Greyoll's Dragonbarrow", name: "Dragonbarrow Cave"},
    PlayRegion { id: 6402001, map: "Greyoll's Dragonbarrow", name: "Bestial Sanctum"},
    PlayRegion { id: 3413003, map: "Greyoll's Dragonbarrow", name: "Divine Tower of Caelid: Center"},
    PlayRegion { id: 3413013, map: "Greyoll's Dragonbarrow", name: "Divine Tower of Caelid: Basement"},
    PlayRegion { id: 3415090, map: "Greyoll's Dragonbarrow", name: "Isolated Divine Tower"},
    PlayRegion { id: 6500000, map: "Forbidden Lands", name: "Forbidden Lands"},
    PlayRegion { id: 6500090, map: "Forbidden Lands", name: "Grand Lift of Rold"},
    PlayRegion { id: 3020001, map: "Forbidden Lands", name: "Hidden Path to the Haligtree"},
    PlayRegion { id: 3020002, map: "Forbidden Lands", name: "Hidden Path to the Haligtree Part II"},
    PlayRegion { id: 3414011, map: "Forbidden Lands", name: "Divine Tower of East Altus"},
    PlayRegion { id: 6501000, map: "Mountaintops of the Giants", name: "Zamor Ruins"},
    PlayRegion { id: 6501001, map: "Mountaintops of the Giants", name: "Central Mountaintops"},
    PlayRegion { id: 6501002, map: "Mountaintops of the Giants", name: "Castle Sol"},
    PlayRegion { id: 3122001, map: "Mountaintops of the Giants", name: "Spiritcaller's Cave"},
    PlayRegion { id: 6501003, map: "Mountaintops of the Giants", name: "Castle Sol Main Gate, Church of the Eclipse"},
    PlayRegion { id: 6501010, map: "Mountaintops of the Giants", name: "Castle Sol Rooftop"},
    PlayRegion { id: 6502000, map: "Flame Peak", name: "Giants' Gravepost, Foot of the Forge"},
    PlayRegion { id: 6502010, map: "Flame Peak", name: "Fire Giant"},
    PlayRegion { id: 3018001, map: "Flame Peak", name: "Giants' Mountaintop Catacombs"},
    PlayRegion { id: 3017002, map: "Flame Peak", name: "Giant-Conquering Hero's Grave"},
    PlayRegion { id: 6503000, map: "Consecrated Snowfield", name: "Consecrated Snowfield"},
    PlayRegion { id: 3019001, map: "Consecrated Snowfield", name: "Consecrated Snowfield Catacombs"},
    PlayRegion { id: 3112001, map: "Consecrated Snowfield", name: "Cave of the Forlorn"},
    PlayRegion { id: 3211001, map: "Consecrated Snowfield", name: "Yelough Anix Tunnel"},
    PlayRegion { id: 1500011, map: "Miquella's Haligtree", name: "Haligtree Canopy"},
    PlayRegion { id: 1500012, map: "Miquella's Haligtree", name: "Haligtree Town Plaza"},
    PlayRegion { id: 1500010, map: "Miquella's Haligtree", name: "Haligtree Promenade"},
    PlayRegion { id: 1500001, map: "Elphael, Brace of the Haligtree", name: "Prayer Room"},
    PlayRegion { id: 1500002, map: "Elphael, Brace of the Haligtree", name: "Elphael Inner Wall, Drainage Channel"},
    PlayRegion { id: 1500003, map: "Elphael, Brace of the Haligtree", name: "Haligtree Roots"},
    PlayRegion { id: 1500000, map: "Elphael, Brace of the Haligtree", name: "Malenia, Goddess of Rot"},
    PlayRegion { id: 1201001, map: "Ainsel River", name: "Ainsel River Well Depths"},
    PlayRegion { id: 1201002, map: "Ainsel River", name: "Ainsel River Downstream"},
    PlayRegion { id: 1201003, map: "Ainsel River", name: "Ainsel River Downstream Part II"},
    PlayRegion { id: 1204000, map: "Ainsel River", name: "Astel, Naturalborn of the Void"},
    PlayRegion { id: 1201000, map: "Ainsel River", name: "Dragonkin Soldier of Nokstella"},
    PlayRegion { id: 1201011, map: "Ainsel River Main", name: "Ainsel River Main"},
    PlayRegion { id: 1201013, map: "Ainsel River Main", name: "Nokstella, Eternal City"},
    PlayRegion { id: 1201014, map: "Ainsel River Main", name: "Nokstella Waterfall Basin"},
    PlayRegion { id: 1201015, map: "Lake of Rot", name: "Lake of Rot Shoreside"},
    PlayRegion { id: 1201016, map: "Lake of Rot", name: "Grand Cloister"},
    PlayRegion { id: 1201017, map: "Lake of Rot", name: "Grand Cloister Part II"},
    PlayRegion { id: 1207026, map: "Nokron, Eternal City", name: "Nokron, Eternal City"},
    PlayRegion { id: 1202020, map: "Nokron, Eternal City", name: "Mimic Tear"},
    PlayRegion { id: 1202002, map: "Nokron, Eternal City", name: "Ancestral Woods"},
    PlayRegion { id: 1202007, map: "Nokron, Eternal City", name: "Night's Sacred Ground"},
    PlayRegion { id: 1202003, map: "Nokron, Eternal City", name: "Aqueduct-Facing Cliffs"},
    PlayRegion { id: 1202004, map: "Nokron, Eternal City", name: "Aqueduct-Facing Cliffs Part II"},
    PlayRegion { id: 1202000, map: "Nokron, Eternal City", name: "Great Waterfall Basin"},
    PlayRegion { id: 1205001, map: "Mohgwyn Palace", name: "Palace Approach Ledge-Road"},
    PlayRegion { id: 1205004, map: "Mohgwyn Palace", name: "Dynasty Mausoleum Entrance"},
    PlayRegion { id: 1205006, map: "Mohgwyn Palace", name: "Dynasty Mausoleum Midpoint"},
    PlayRegion { id: 1205000, map: "Mohgwyn Palace", name: "Cocoon of the Empyrean"},
    PlayRegion { id: 1207031, map: "Siofra River", name: "Siofra River Well Depths"},
    PlayRegion { id: 1202033, map: "Siofra River", name: "Siofra River Bank"},
    PlayRegion { id: 1202034, map: "Siofra River", name: "Worshippers' Woods"},
    PlayRegion { id: 1203001, map: "Deeproot Depths", name: "Root-Facing Cliffs"},
    PlayRegion { id: 1203002, map: "Deeproot Depths", name: "Great Waterfall Crest Part II"},
    PlayRegion { id: 1203003, map: "Deeproot Depths", name: "Deeproot Depths"},
    PlayRegion { id: 1203004, map: "Deeproot Depths", name: "The Nameless Eternal City"},
    PlayRegion { id: 1203005, map: "Deeproot Depths", name: "Across the Roots"},
    PlayRegion { id: 1203000, map: "Deeproot Depths", name: "Prince of Death's Throne"},
    PlayRegion { id: 1300012, map: "Crumbling Farum Azula", name: "Crumbling Beast Grave"},
    PlayRegion { id: 1300013, map: "Crumbling Farum Azula", name: "Crumbling Beast Grave Depths, Tempest-Facing Balcony"},
    PlayRegion { id: 1300017, map: "Crumbling Farum Azula", name: "Dragon Temple"},
    PlayRegion { id: 1300018, map: "Crumbling Farum Azula", name: "Dragon Temple Transept"},
    PlayRegion { id: 1300010, map: "Crumbling Farum Azula", name: "Dragon Temple Altar"},
    PlayRegion { id: 1300019, map: "Crumbling Farum Azula", name: "Dragon Temple Lift"},
    PlayRegion { id: 1300003, map: "Crumbling Farum Azula", name: "Dragon Temple Rooftop"},
    PlayRegion { id: 1300020, map: "Crumbling Farum Azula", name: "Dragonlord Placidusax"},
    PlayRegion { id: 1300006, map: "Crumbling Farum Azula", name: "Beside the Great Bridge"},
    PlayRegion { id: 1300000, map: "Crumbling Farum Azula", name: "Maliketh, the Black Blade"},
];
