use serde::{Serialize, Deserialize};

use super::*;

#[derive(Serialize, Deserialize, Debug)]
#[repr(u32)]
pub enum RequestParams {
    CreateSession(Box<session::RequestCreateSessionParams>),
    DeleteSession,
    RestoreSession(Box<session::RequestRestoreSessionParams>),
    DebugCommand,
    ServerPing,
    CheckAlive,
    GetAnnounceMessageList(Box<announcement::RequestGetAnnounceMessageListParams>),
    UpdateLoginPlayerCharacter,
    SystemLog,
    MenuUsageLog,
    InGameResultLog,
    UploadFamilySharingInfo,
    UploadGuardITCode,
    CreateMatchingTicket(Box<matchingticket::RequestCreateMatchingTicketParams>),
    PollMatchingTicket,
    DeleteMatchingTicket,
    StartBattleSession,
    FinishBattleSession,
    CreateBattleSession,
    CreateRoom,
    UpdateRoom,
    DeleteRoom,
    GetRoom,
    GetRoomList,
    GenerateRoomBattleID,
    RegisterUGC,
    GetUGCIDList,
    GetUGC,
    DeleteUGC,
    GetUGCStatus,
    GenerateUGCServerID,
    KeepUGCServerID,
    UpdatePlayerProperties,
    GetPlayerProperties,
    GetRankingOrder,
    GetRatingStatus,
    GetPlayerRatingValue,
    Report,
    Healthcheck,
}

impl RequestParams {
    pub fn name(&self) -> &'static str {
        match self {
            Self::CreateSession(_) => "CreateSession",
            Self::DeleteSession => "DeleteSession",
            Self::RestoreSession(_) => "RestoreSession",
            Self::DebugCommand => "DebugCommand",
            Self::ServerPing => "ServerPing",
            Self::CheckAlive => "CheckAlive",
            Self::GetAnnounceMessageList(_) => "GetAnnounceMessageList",
            Self::UpdateLoginPlayerCharacter => "UpdateLoginPlayerCharacter",
            Self::SystemLog => "SystemLog",
            Self::MenuUsageLog => "MenuUsageLog",
            Self::InGameResultLog => "InGameResultLog",
            Self::UploadFamilySharingInfo => "UploadFamilySharingInfo",
            Self::UploadGuardITCode => "UploadGuardITCode",
            Self::CreateMatchingTicket(_) => "CreateMatchingTicket",
            Self::PollMatchingTicket => "PollMatchingTicket",
            Self::DeleteMatchingTicket => "DeleteMatchingTicket",
            Self::StartBattleSession => "StartBattleSession",
            Self::FinishBattleSession => "FinishBattleSession",
            Self::CreateBattleSession => "CreateBattleSession",
            Self::CreateRoom => "CreateRoom",
            Self::UpdateRoom => "UpdateRoom",
            Self::DeleteRoom => "DeleteRoom",
            Self::GetRoom => "GetRoom",
            Self::GetRoomList => "GetRoomList",
            Self::GenerateRoomBattleID => "GenerateRoomBattleID",
            Self::RegisterUGC => "RegisterUGC",
            Self::GetUGCIDList => "GetUGCIDList",
            Self::GetUGC => "GetUGC",
            Self::DeleteUGC => "DeleteUGC",
            Self::GetUGCStatus => "GetUGCStatus",
            Self::GenerateUGCServerID => "GenerateUGCServerID",
            Self::KeepUGCServerID => "KeepUGCServerID",
            Self::UpdatePlayerProperties => "UpdatePlayerProperties",
            Self::GetPlayerProperties => "GetPlayerProperties",
            Self::GetRankingOrder => "GetRankingOrder",
            Self::GetRatingStatus => "GetRatingStatus",
            Self::GetPlayerRatingValue => "GetPlayerRatingValue",
            Self::Report => "Report",
            Self::Healthcheck => "Healthcheck",
        }
    }
}
